This model uses the popularity attribute as well as the average rating and voter count in the TMDB data to generate popular movies genre wise. The genres are determined using the IMDB data.

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from ast import literal_eval

In [12]:
movies = pd.read_csv("movies_tmdb.csv")

In [13]:
movies.sort_values(by='popularity', ascending=False)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
546,74000000,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 16, ""...",http://www.minionsmovie.com/,211672,"[{""id"": 3487, ""name"": ""assistant""}, {""id"": 179...",en,Minions,"Minions Stuart, Kevin and Bob are recruited by...",875.581305,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-06-17,1156730962,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Before Gru, they had a history of bad bosses",Minions,6.4,4571
95,165000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",http://www.interstellarmovie.net/,157336,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Interstellar,Interstellar chronicles the adventures of a gr...,724.247784,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",2014-11-05,675120017,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Mankind was born on Earth. It was never meant ...,Interstellar,8.1,10867
788,58000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.foxmovies.com/movies/deadpool,293660,"[{""id"": 2095, ""name"": ""anti hero""}, {""id"": 307...",en,Deadpool,Deadpool tells the origin story of former Spec...,514.569956,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-02-09,783112979,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Witness the beginning of a happy ending,Deadpool,7.4,10995
94,170000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""na...",http://marvel.com/guardians,118340,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Guardians of the Galaxy,"Light years from Earth, 26 years after being a...",481.098624,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2014-07-30,773328629,121.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,All heroes start somewhere.,Guardians of the Galaxy,7.9,9742
127,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.madmaxmovie.com/,76341,"[{""id"": 2964, ""name"": ""future""}, {""id"": 3713, ...",en,Mad Max: Fury Road,An apocalyptic story set in the furthest reach...,434.278564,"[{""name"": ""Village Roadshow Pictures"", ""id"": 7...","[{""iso_3166_1"": ""AU"", ""name"": ""Australia""}, {""...",2015-05-13,378858340,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What a Lovely Day.,Mad Max: Fury Road,7.2,9427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4625,0,"[{""id"": 27, ""name"": ""Horror""}]",NaN,426067,[],en,Midnight Cabaret,A Broadway producer puts on a play with a Devi...,0.001389,[],[],1990-01-01,0,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The hot spot where Satan's waitin'.,Midnight Cabaret,0.0,0
4118,0,[],NaN,325140,[],en,Hum To Mohabbat Karega,"Raju, a waiter, is in love with the famous TV ...",0.001186,[],[],2000-05-26,0,0.0,[],Released,NaN,Hum To Mohabbat Karega,0.0,0
4727,0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,65448,"[{""id"": 378, ""name"": ""prison""}, {""id"": 209476,...",en,Penitentiary,A hitchhiker named Martel Gordone gets in a fi...,0.001117,[],[],1979-12-01,0,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"There's only one way out, and 100 fools stand ...",Penitentiary,4.9,8
3361,0,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 28, ""nam...",NaN,77156,[],en,Alien Zone,A man who is having an affair with a married w...,0.000372,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1978-11-22,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Don't you dare go in there!,Alien Zone,4.0,3
4553,0,[],NaN,380097,[],en,America Is Still the Place,1971 post civil rights San Francisco seemed li...,0.000000,[],[],NaN,0,0.0,[],Released,NaN,America Is Still the Place,0.0,0

## Genres

 'Adventure'<br>
 'Animation'<br>
 'Children'<br>
 'Comedy'<br>
 'Fantasy'<br>
 'Romance'<br>
 'Drama'<br>
 'Action'<br>
 'Crime'<br>
 'Thriller'<br>
 'Horror'<br>
 'Mystery'<br>
 'Sci-Fi'<br>
 'War'<br>
 'Musical'<br>
 'Documentary'<br>
 'IMAX'<br>
 'Western'<br>
 'Film-Noir'<br>
 '(no genres listed)'<br>

In [15]:
genres = {'Adventure': 0,
 'Animation': 1,
 'Children': 2,
 'Comedy': 3,
 'Fantasy': 4,
 'Romance': 5,
 'Drama': 6,
 'Action': 7,
 'Crime': 8,
 'Thriller': 9,
 'Horror': 10,
 'Mystery': 11,
 'Sci-Fi': 12,
 'War': 13,
 'Musical': 14,
 'Documentary': 15,
 'IMAX': 16,
 'Western': 17,
 'Film-Noir': 18,
 '(no genres listed)': 19}

In [16]:
def genre_based_popularity(genre):
    mask = movies.genres.apply(lambda x: genre in x)
    filtered_movie = movies[mask]
    filtered_movie = filtered_movie.sort_values(by='popularity', ascending=False)
    return filtered_movie

In [17]:
genre_based_popularity('Animation')[['title', 'popularity']].head(25)

                                title  popularity
546                           Minions  875.581305
88                         Big Hero 6  203.734590
124                            Frozen  165.125366
506                   Despicable Me 2  136.886704
77                         Inside Out  128.655964
55                              Brave  125.114374
2294                    Spirited Away  118.968562
614                     Despicable Me  113.858273
231                    Monsters, Inc.  106.815545
160        How to Train Your Dragon 2  100.213910
631                           Ice Age   99.561972
1695                          Aladdin   92.982009
66                                 Up   92.201962
494                     The Lion King   90.457886
190          The Adventures of Tintin   89.938296
34                Monsters University   89.186492
1062                     A Bug's Life   87.350802
328                      Finding Nemo   85.688789
514             Ice Age: The Meltdown   85.115058
181                     Kung Fu Panda   84.689648
179            Penguins of Madagascar   84.366984
566                              Cars   82.643036
4259  Snow White and the Seven Dwarfs   80.171283
339                   The Incredibles   77.817571
1541                        Toy Story   73.640445

In [18]:
genre_based_popularity('Romance')[['title', 'popularity']].head(25)

                                          title  popularity
809                                Forrest Gump  138.133331
1337                                   Twilight  127.084938
81                                   Maleficent  110.620647
612                  The Twilight Saga: Eclipse  107.069763
326                                  Cinderella  101.187052
25                                      Titanic  100.025899
172   The Twilight Saga: Breaking Dawn - Part 2   99.687084
1154                       Fifty Shades of Grey   98.755657
898                 The Twilight Saga: New Moon   94.815867
1695                                    Aladdin   92.982009
2313                                   The Mask   85.303180
1366                      The Devil Wears Prada   83.893257
1599                         The Age of Adaline   82.052056
2838                     The Fault in Our Stars   74.358971
1260                                     Amélie   73.720244
1352                                    Gattaca   70.398356
3444                                     Grease   67.608041
2847                                Paper Towns   64.610671
2071                    Silver Linings Playbook   63.599973
269                   The Princess and the Frog   62.479574
50          Prince of Persia: The Sands of Time   62.169881
515                              50 First Dates   61.437586
49                             The Great Gatsby   61.196071
2547                   The Theory of Everything   61.182331
2810                               American Pie   60.767168

In [19]:
genre_based_popularity('Action')[['title', 'popularity']].head(25)

                                                  title  popularity
788                                            Deadpool  514.569956
94                              Guardians of the Galaxy  481.098624
127                                  Mad Max: Fury Road  434.278564
28                                       Jurassic World  418.708552
199   Pirates of the Caribbean: The Curse of the Bla...  271.972889
82                       Dawn of the Planet of the Apes  243.791743
88                                           Big Hero 6  203.734590
108                                  Terminator Genisys  202.042635
26                           Captain America: Civil War  198.372395
65                                      The Dark Knight  187.322927
96                                            Inception  167.583710
9                    Batman v Superman: Dawn of Justice  155.790452
0                                                Avatar  150.437577
12           Pirates of the Caribbean: Dead Man's Chest  145.847379
16                                         The Avengers  144.448633
238                        Teenage Mutant Ninja Turtles  143.350376
362                                              Pixels  140.849495
456                                                Fury  139.575085
1              Pirates of the Caribbean: At World's End  139.082615
335                      Rise of the Planet of the Apes  138.433168
262   The Lord of the Rings: The Fellowship of the Ring  138.049577
17          Pirates of the Caribbean: On Stranger Tides  135.413856
7                               Avengers: Age of Ultron  134.279229
1465                                    The Maze Runner  131.815575
102               The Hunger Games: Mockingjay - Part 2  127.284427

## Calculate the weighted rating

In [21]:
# this is V
vote_counts = movies[movies['vote_count'].notnull()]['vote_count'].astype('int')

# this is R
vote_averages = movies[movies['vote_average'].notnull()]['vote_average'].astype('int')

# this is C
C = vote_averages.mean()
C

5.6529252550489275

In [22]:
m = vote_counts.quantile(0.95)
m

3040.8999999999996

In [23]:
def weighted_rating(x):
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v) * C)

In [24]:
movies['wr'] = movies.apply(weighted_rating, axis=1)

In [25]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,wr
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,6.883004
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,6.397112
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,6.037883
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,7.112562
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,5.836779

In [26]:
def genre_based_popularity_PT(genre):
    mask = movies.genres.apply(lambda x: genre in x)
    filtered_movie = movies[mask]
    filtered_movie = filtered_movie.sort_values(by='wr', ascending=False)
    return filtered_movie

In [27]:
genre_based_popularity_PT('Animation')[['title', 'wr', 'popularity']].head(10)

               title        wr  popularity
77        Inside Out  7.256609  128.655964
494    The Lion King  7.152037   90.457886
2294   Spirited Away  7.130169  118.968562
57            WALL·E  7.100727   66.390712
88        Big Hero 6  7.088458  203.734590
66                Up  7.071909   92.201962
328     Finding Nemo  6.953823   85.688789
1541       Toy Story  6.950900   73.640445
231   Monsters, Inc.  6.878463  106.815545
42       Toy Story 3  6.824805   59.995418

In [28]:
genre_based_popularity_PT('Action')[['title', 'wr', 'popularity']].head(25)

                                                  title        wr  popularity
65                                      The Dark Knight  7.685113  187.322927
96                                            Inception  7.656878  167.583710
329       The Lord of the Rings: The Return of the King  7.429908  123.630332
262   The Lord of the Rings: The Fellowship of the Ring  7.392365  138.049577
94                              Guardians of the Galaxy  7.365448  481.098624
1990                            The Empire Strikes Back  7.331672   78.517830
2912                                          Star Wars  7.330069  126.393695
634                                          The Matrix  7.328089  104.309993
330               The Lord of the Rings: The Two Towers  7.322066  106.914973
571                                Inglourious Basterds  7.178513   72.595961
3                                 The Dark Knight Rises  7.112562  112.312950
274                                           Gladiator  7.094197   95.301296
88                                           Big Hero 6  7.088458  203.734590
16                                         The Avengers  7.041445  144.448633
788                                            Deadpool  7.021493  514.569956
1490                                 Return of the Jedi  7.013260   46.509071
3158                                              Alien  6.990238   94.184658
119                                       Batman Begins  6.959921  115.040024
68                                             Iron Man  6.950417  120.725053
199   Pirates of the Caribbean: The Curse of the Bla...  6.939774  271.972889
85                  Captain America: The Winter Soldier  6.927549   72.225265
828                                   Kill Bill: Vol. 1  6.920898   79.754966
0                                                Avatar  6.883004  150.437577
46                           X-Men: Days of Future Past  6.880929  118.078691
932                                      V for Vendetta  6.868110   84.630969

In [29]:
genre_based_popularity_PT('Romance')[['title', 'wr', 'popularity']].head(25)

                                      title        wr  popularity
809                            Forrest Gump  7.493812  138.133331
25                                  Titanic  6.970261  100.025899
1997                                    Her  6.942697   53.682367
2152  Eternal Sunshine of the Spotless Mind  6.879048   56.481487
2547               The Theory of Everything  6.772112   61.182331
1260                                 Amélie  6.771950   73.720244
2838                 The Fault in Our Stars  6.729273   74.358971
1559                           The Notebook  6.680836   55.109138
493                        A Beautiful Mind  6.671066   59.248437
2776        The Perks of Being a Wallflower  6.664045   43.444135
2108                    Edward Scissorhands  6.654343   47.513630
2666                    Slumdog Millionaire  6.590975   59.258969
1695                                Aladdin  6.577209   92.982009
49                         The Great Gatsby  6.564513   61.196071
2109                          Me Before You  6.543251   53.161905
100     The Curious Case of Benjamin Button  6.509116   60.269279
81                               Maleficent  6.456498  110.620647
2071                Silver Linings Playbook  6.412749   63.599973
3339                   (500) Days of Summer  6.408649   45.610993
2659                          Groundhog Day  6.405470   52.744331
4329                             Casablanca  6.368904   43.729123
2422                          Pitch Perfect  6.352821   32.746486
1599                     The Age of Adaline  6.343990   82.052056
1579                      Midnight in Paris  6.343990   43.753585
1352                                Gattaca  6.341640   70.398356